#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyLexics.Resource", IsApplication=true)]

namespace MyLexics
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int move_left2 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int move_left3 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int move_left4 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int move_right2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int move_right3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int move_right4 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int slide_in_left = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int slide_in_right = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int slide_left = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int slide_out_left = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int slide_out_right = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int zoom_in = 2131034123;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Abjad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Abjad_Button_a = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Abjad_Button_b = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Abjad_Button_c = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Abjad_Button_d = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Abjad_Button_e = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Abjad_Button_e2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Abjad_Button_f = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Abjad_Button_g = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Abjad_Button_h = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Abjad_Button_i = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Abjad_Button_j = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Abjad_Button_k = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Abjad_Button_l = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Abjad_Button_m = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Abjad_Button_n = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Abjad_Button_o = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Abjad_Button_p = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Abjad_Button_q = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Abjad_Button_r = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Abjad_Button_s = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Abjad_Button_t = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Abjad_Button_u = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Abjad_Button_v = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Abjad_Button_w = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Abjad_Button_x = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Abjad_Button_y = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Abjad_Button_z = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Abjad_main_OrangeBG = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Abjad_Stroke_BrownCircleBG = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Abjad_Stroke_BrownCircleBGnew = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Abjad_title = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int AbjadBackground = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int activitigrey = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Activitilock = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Aktiviti = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int api = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int arrowL = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int arrowR = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int awam = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ayam = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ba = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Back_Button = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int bagus = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int baju = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int bas = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int batik01 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int batuk01 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int be = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int beku01 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int betik01 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int bi = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int biru = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int blank = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int bo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int bola = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int bola2 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int bu = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int buka01 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int buku01 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Button_start = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Button_vokal = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ca = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int catuk01 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int cawan = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ce = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ceri = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ci = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int cicak = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int cicak2 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int co = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int cu = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int cucuk01 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int cuka01 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int cyberlock = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int da = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int dadu = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int dakap01 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int dapat01 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int datuk01 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int de = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int detik01 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int di = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int doo = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int du = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int duka01 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int duku01 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int duri = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int duri2 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int durian = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ekor = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int emak = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int emas = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int enam = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int epal = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int fa = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int fe = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int feri = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int fi = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int filem = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int fo = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int foto = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int fu = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ga = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int gajah = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ge = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int gi = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int go = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int gu = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int gula = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int guli = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int hero = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int hoki = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int hon = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int ibu = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int ic_clear_black_24dp = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int ic_done_black_24dp = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int icon = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int ikan = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int itik = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int jala = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int jam = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int jari = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int kaku01 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int katak = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int katik01 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int keju = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int Keluarga_Perkataan_title = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int Kenali_Vokal_Title = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int Kenanli_Konsonan_title = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int Kenanli_Sukukata_title = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int Konsonan_Bergamabr_title = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int Konsonan_Button = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int KonsonanBergamber_Button_temp = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int kuda = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int kuku01 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int laci = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int lekat01 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int lepat01 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int liku01 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int lilin = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int lipat01 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int lori = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int luka01 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int lumut01 = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int luput01 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int madu = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int mata = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int meja = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int muka01 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int naga = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int nasi = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int nuri = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int obor = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int Option_Help = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int Option_info = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int Option_Setting = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int Option_survey = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int oren = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int otak = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int p1 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int p10 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int p11 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int p12 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int p13 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int p14 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int p15 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int p2 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int p3 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int p4 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int p5 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int p6 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int p7 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int p8 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int p9 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int paku = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int paku01 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int patuk01 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int pen = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int Perkataan = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int Perkataanlock = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int petik01 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int pos = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int price = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int pucuk01 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int qari = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int roda = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int ros = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int roti = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int saku01 = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int selection = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int semut = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int setting = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int spearlogo = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int Splash = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int start = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int SubSubMenu_Background = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int suka01 = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int Sukukata = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int Sukukatalock = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int sup = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int susu = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int tali = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int topi = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int tukul = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int tusuk01 = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int ubi = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int ular = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int ulat = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int van = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int vas = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int video = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int Vokal_Bergambar_title = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int Vokal_Button = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int Vokal_selection = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int VokalBergambar_Button = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int wang = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int wau = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int wayar = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public const int xray = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public const int xray2 = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public const int yoyo = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public const int yu = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public const int zip = 2130837727;
			
			// aapt resource value: 0x7f0200e0
			public const int zirafah = 2130837728;
			
			// aapt resource value: 0x7f0200e1
			public const int zoo = 2130837729;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090003
			public const int AbjadBergambarVideoBackBtn = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int AbjadBergambarVideoInfoBtn = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int AbjadBergambarVideoLeftBtn = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int AbjadBergambarVideoRightBtn = 2131296262;
			
			// aapt resource value: 0x7f090010
			public const int AbjadKonsonanBergambarUIBackButton = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int AbjadKonsonanBergambarUIInfoButton = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int AbjadKonsonanBergambarUILeftButton = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int AbjadKonsonanBergambarUIRightButton = 2131296277;
			
			// aapt resource value: 0x7f090011
			public const int AbjadKonsonanBergambarUITitle = 2131296273;
			
			// aapt resource value: 0x7f090014
			public const int AbjadKonsonanBergambarhorizontalSV = 2131296276;
			
			// aapt resource value: 0x7f090008
			public const int AbjadKonsonanUIBackButton = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int AbjadKonsonanUIInfoButton = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int AbjadKonsonanUILeftButton = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int AbjadKonsonanUIRightButton = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int AbjadKonsonanUITitle = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int AbjadKonsonanhorizontalSV = 2131296268;
			
			// aapt resource value: 0x7f09001d
			public const int AbjadSelectionKonsonanBergambarButton = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int AbjadSelectionKonsonanButton = 2131296284;
			
			// aapt resource value: 0x7f090017
			public const int AbjadSelectionUIBackButton = 2131296279;
			
			// aapt resource value: 0x7f090019
			public const int AbjadSelectionUIInfoButton = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int AbjadSelectionUITitle = 2131296280;
			
			// aapt resource value: 0x7f09001b
			public const int AbjadSelectionVokalBergambarButton = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int AbjadSelectionVokalButton = 2131296282;
			
			// aapt resource value: 0x7f090021
			public const int AbjadVideoBackBtn = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int AbjadVideoExample1 = 2131296291;
			
			// aapt resource value: 0x7f090025
			public const int AbjadVideoExample2 = 2131296293;
			
			// aapt resource value: 0x7f090027
			public const int AbjadVideoExample3 = 2131296295;
			
			// aapt resource value: 0x7f090041
			public const int AbjadVideoExample4 = 2131296321;
			
			// aapt resource value: 0x7f090043
			public const int AbjadVideoExample5 = 2131296323;
			
			// aapt resource value: 0x7f090045
			public const int AbjadVideoExample6 = 2131296325;
			
			// aapt resource value: 0x7f090047
			public const int AbjadVideoExample7 = 2131296327;
			
			// aapt resource value: 0x7f090049
			public const int AbjadVideoExample8 = 2131296329;
			
			// aapt resource value: 0x7f090022
			public const int AbjadVideoExampleLinearLayout1 = 2131296290;
			
			// aapt resource value: 0x7f090024
			public const int AbjadVideoExampleLinearLayout2 = 2131296292;
			
			// aapt resource value: 0x7f090026
			public const int AbjadVideoExampleLinearLayout3 = 2131296294;
			
			// aapt resource value: 0x7f090040
			public const int AbjadVideoExampleLinearLayout4 = 2131296320;
			
			// aapt resource value: 0x7f090042
			public const int AbjadVideoExampleLinearLayout5 = 2131296322;
			
			// aapt resource value: 0x7f090044
			public const int AbjadVideoExampleLinearLayout6 = 2131296324;
			
			// aapt resource value: 0x7f090046
			public const int AbjadVideoExampleLinearLayout7 = 2131296326;
			
			// aapt resource value: 0x7f090048
			public const int AbjadVideoExampleLinearLayout8 = 2131296328;
			
			// aapt resource value: 0x7f090029
			public const int AbjadVideoInfoBtn = 2131296297;
			
			// aapt resource value: 0x7f090028
			public const int AbjadVideoLeftBtn = 2131296296;
			
			// aapt resource value: 0x7f09002a
			public const int AbjadVideoRightBtn = 2131296298;
			
			// aapt resource value: 0x7f090034
			public const int AbjadVokalBergambarUIBackButton = 2131296308;
			
			// aapt resource value: 0x7f090036
			public const int AbjadVokalBergambarUIInfoButton = 2131296310;
			
			// aapt resource value: 0x7f090037
			public const int AbjadVokalBergambarUILeftButton = 2131296311;
			
			// aapt resource value: 0x7f090039
			public const int AbjadVokalBergambarUIRightButton = 2131296313;
			
			// aapt resource value: 0x7f090035
			public const int AbjadVokalBergambarUITitle = 2131296309;
			
			// aapt resource value: 0x7f090038
			public const int AbjadVokalBergambarhorizontalSV = 2131296312;
			
			// aapt resource value: 0x7f09002c
			public const int AbjadVokalUIBackButton = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int AbjadVokalUIInfoButton = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int AbjadVokalUILeftButton = 2131296303;
			
			// aapt resource value: 0x7f090032
			public const int AbjadVokalUIRightButton = 2131296306;
			
			// aapt resource value: 0x7f09002d
			public const int AbjadVokalUITitle = 2131296301;
			
			// aapt resource value: 0x7f090030
			public const int AbjadVokalhorizontalSV = 2131296304;
			
			// aapt resource value: 0x7f09003a
			public const int ContactDetails = 2131296314;
			
			// aapt resource value: 0x7f09003e
			public const int LockDetails = 2131296318;
			
			// aapt resource value: 0x7f09003d
			public const int btnExitCancel = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public const int btnExitOK = 2131296316;
			
			// aapt resource value: 0x7f09003b
			public const int exitQuestion = 2131296315;
			
			// aapt resource value: 0x7f09003f
			public const int imageView = 2131296319;
			
			// aapt resource value: 0x7f090000
			public const int linearLayoutAbjadBergambarVideoBack = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int linearLayoutAbjadBergambarVideoFront = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int linearLayoutAbjadKonsonan = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int linearLayoutAbjadKonsonanBergambar = 2131296271;
			
			// aapt resource value: 0x7f090016
			public const int linearLayoutAbjadSelection = 2131296278;
			
			// aapt resource value: 0x7f09001e
			public const int linearLayoutAbjadVideoBack = 2131296286;
			
			// aapt resource value: 0x7f090020
			public const int linearLayoutAbjadVideoFront = 2131296288;
			
			// aapt resource value: 0x7f09002b
			public const int linearLayoutAbjadVokal = 2131296299;
			
			// aapt resource value: 0x7f090033
			public const int linearLayoutAbjadVokalBergambar = 2131296307;
			
			// aapt resource value: 0x7f09000d
			public const int linearLayoutScrollViewKonsonan = 2131296269;
			
			// aapt resource value: 0x7f090031
			public const int linearLayoutScrollViewVokal = 2131296305;
			
			// aapt resource value: 0x7f09004a
			public const int linearLayoutSelection = 2131296330;
			
			// aapt resource value: 0x7f090054
			public const int linearLayoutSplash = 2131296340;
			
			// aapt resource value: 0x7f09004b
			public const int selectionUIBackButton = 2131296331;
			
			// aapt resource value: 0x7f09004d
			public const int selectionUIHelpBtn = 2131296333;
			
			// aapt resource value: 0x7f09004f
			public const int selectionUIInfoBtn = 2131296335;
			
			// aapt resource value: 0x7f090050
			public const int selectionUIModuleAbjadBtn = 2131296336;
			
			// aapt resource value: 0x7f090053
			public const int selectionUIModuleAktivitiBtn = 2131296339;
			
			// aapt resource value: 0x7f090052
			public const int selectionUIModulePerkataanBtn = 2131296338;
			
			// aapt resource value: 0x7f090051
			public const int selectionUIModuleSukukataBtn = 2131296337;
			
			// aapt resource value: 0x7f09004e
			public const int selectionUISettingBtn = 2131296334;
			
			// aapt resource value: 0x7f09004c
			public const int selectionUISurveyBtn = 2131296332;
			
			// aapt resource value: 0x7f090001
			public const int videoBergambarView = 2131296257;
			
			// aapt resource value: 0x7f09001f
			public const int videoView = 2131296287;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AbjadBergambarVideoLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AbjadKonsonan = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AbjadKonsonanBergambar = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AbjadSelection = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int AbjadVideoLayout = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int AbjadVokal = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int AbjadVokalBergambar = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ContactInformation = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ExitDialog = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int LockInformation = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int PerkataanSelection = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int PerkataanVideoLayout = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Selection = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int SplashLayout = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int SukukataSelection = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int SukukataVideoLayout = 2130968591;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int A = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ayam = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int B = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ba = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int bagus = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int batik = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int batuk = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int be = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int beku = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int betik = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int bi = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int bo = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int bu = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int buka = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int buku = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int C = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int catuk = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int cicak = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int cucuk = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int cuka = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int D = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int dakap = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int dapat = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int datuk = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int detik = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int duka = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int duku = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int duri = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int E = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int EA = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int enam = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int example_bas = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int example_bola = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int example_cawan = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int example_ceri = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int example_cicak = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int example_dadu = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int example_duri = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int example_feri = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int example_filem = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int example_foto = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int example_gajah = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int example_guli = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int example_hoki = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int example_hon = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int example_jala = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int example_jam = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int example_jari = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int example_keju = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int example_kuda = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int example_laci = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int example_lilin = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int example_lori = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int example_madu = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int example_mata = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int example_meja = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int example_naga = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int example_nasi = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int example_nuri = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int example_paku = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int example_pen = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int example_pos = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int example_qari = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int example_roda = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int example_ros = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int example_roti = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int example_sup = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int example_susu = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int example_tali = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int example_topi = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int example_try = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int example_tukul = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int example_vas = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int example_video = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int example_wang = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int example_wau = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int example_xray = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int example_yoyo = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int example_yu = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int example_zip = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int example_zirafah = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int example_zoo = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int examples_api = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int examples_awam = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int examples_ayam = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int examples_ekor = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int examples_emak = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int examples_emas = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int examples_enam = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int examples_epal = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int examples_ibu = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int examples_ikan = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int examples_itik = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int examples_obor = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int examples_oren = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int examples_otak = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int examples_ubi = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int examples_ular = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int examples_ulat = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int F = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int filem = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int G = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int gajah = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int H = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int hero = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int I = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int itik = 2131099754;
			
			// aapt resource value: 0x7f06006b
			public const int J = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int jam = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int K = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int kaku = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int katak = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int katik = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int kuku = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int L = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int lekat = 2131099763;
			
			// aapt resource value: 0x7f060074
			public const int lepat = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int liku = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int lilin = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int lipat = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int luka = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int lumut = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int luput = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int M = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int meja = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int muka = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int N = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int naga = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int O = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int oren = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int P = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int paku = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int patuk = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int pen = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int petik = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int pucuk = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int Q = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int qari = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int R = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int roti = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int S = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int saku = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int selamatdatang = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int semut = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int suka = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int T = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int tukul = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int tusuk = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int U = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int ular = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int V = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int vas = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int W = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int wayar = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int X = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int xray = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int Y = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int yoyo = 2131099805;
			
			// aapt resource value: 0x7f06009e
			public const int Z = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int zip = 2131099807;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int AppTheme_AlertDialog = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int Theme_Menu = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
